### ISSUE TITLE
Exploring patient directories in NPF

### ISSUE THREAD

**Issue by hajerkr** [ErasmusMC-NeuroOnco/DeepDicomSort#17]
Hello,

I am trying to run DeepDicomSort at the moment, but I have a hunch that my directory hierarchy doesn't work with the way the algorithm outputs files without deleting anything it has previously computed. Essentially, this is the structure of my folders: 

`PatientID/MR/SessionNum/DICOMSequenceFolder/`

PatientID: string of numbers
MR: subfolder with the name _MR_ , every patient folder has it
SessionNum: a string of numbers, a patient can have more than one timepoint
DICOMSequenceFolder: Folder containing the dicom files. Obviosuly there are multiple folders, with different names. 

For example for one patient, you'll have:
389859405/MR/20382374/Ax_DWI_1000b
389859405/MR/20382374/Ax_T2_GRE
389859405/MR/20382374/Sag_T2_FSE_L-R

etc.

As of now, it's still preprocessing, and I am ending up with one DATA folder under 389859405/MR/20382374/DATA/  (refer to screenshot below).
My concern is, is it creating one labels.txt per patient (in my case per patient/session), or is it supposed to create one data folder per DICOM folder specified in config.yaml ? Because in the latter case, it might be overwriting what it produced for other dicom folders for that patient, if it's saving it to ../DICOMSequenceFolder. I hope this all makes sense, happy to answer any questions you may have.

![image](https://user-images.githubusercontent.com/13291010/162617380-7c13a93b-272e-40e8-b04c-733d70da0f29.png)

**Comment by Svdvoort** [comment]
Can I ask what you put as the `root_dicom_folder` in `config.yaml`? 

If you look in the [preparation function](https://github.com/Svdvoort/DeepDicomSort/blob/master/Preprocessing/DICOM_preparation_functions.py), you see that it takes the parent of that folder to to put the `DICOM_STRUCTURED` folder etc in. That folder should already appear in the root directory, not in the scan directory like in your case.

Let's say your a folder for a specific scan is this: 

`/home/hajerkr/ScanData/PatientID/MR/SessionNum/DICOMSequenceFolder/`

Then the `root_dicom_folder` should be:

`/home/hajerkr/ScanData`

The pre-processing will automatically descend through all the lower level folders/files to find DICOM files. 

This does resolve your issue?

**Comment by hajerkr** [comment]
I modified the preprocessing_pipeline.py script a little bit, I made accept an argument `DICOM_FOLDER` which is passed in the loop as I read from a text file the list of dicoms folders I have. So I pass:

`/home/hajerkr/ScanData/PatientID/MR/SessionNum/DICOMSequenceFolder/`

It's great if I don't need to loop through everything in that case, if it will automatically walk the directory down the the lowest level. **In that case, where will the `DATA/` folder be saved for every session?** 

Will try this now and let you know if I encounter any issues :) 

One more thing, the output of the NIFTI files I see at the moment is a very long string (probably from the DCM headers), but it does not reference the DICOM folder name (e.g.: T2_AX_1MM), **which variable is the folder name saved to in the [convert_DICOM_to_NIFIT] (https://github.com/Svdvoort/DeepDicomSort/blob/master/Preprocessing/NIFTI_preparation_functions.py) function** ?

**Comment by Svdvoort** [comment]
> In that case, where will the DATA/ folder be saved for every session? 

There will be one single `DATA` folder that will contain the data for all sessions, this folder will be stored under the main root folder.
So the best would be to set-up like this:
- Create a DICOM folder in which you put all your data (e.g. `/home/hajerkr/ScanData/DICOM`)
- Use `/home/hajerkr/ScanData/DICOM` as the `root_dicom_folder` in the `config.yaml`
- The DATA folder (and all other folders) will now be created under `/home/hajerkr/`

> Which variable is the folder name saved to
It is not. When converting to NIFTI it uses the name provided by dcm2niix, which is based on the DICOM headers. This is also done to ensure uniqueness in the file names.
However, the file with the final predictions will contain the full (original) path to the DICOM folder along with the prediction, so there you do have that information.

**Comment by hajerkr** [comment]
Thanks very much for your prompt response! I just fired up the script, and passed the main folder that has all patient folders (I still have to keep the stucture Patient/SessionNum/DICOMSeqFolders so I hope that's okay). I am starting to see the DICOM_STRUCTURED folder now, one directory up from the main patient folder.
From my understanding it should work fine, but will ping you if I encounter any issues / have questions. Thanks again :)

**Comment by hajerkr** [comment]
> 

Heya again, just wanted to circle back with regards to the final file naming used here. You mentioned that the final predictions will contain the full (original) path to the DICOM folder. But I'm getting the following: 

`/home/hajerkr/NIFTI_SLICES/1053202153__20200129__MR__1.2.840.113654.2.70.1.313531726791507458836896066765452860929__1.2.840.113654.2.70.1.244649490914256453820682437713251151365_Scan_1_0.nii.gz`

In this case I am losing the SessionNum, under which all the DICOM folders are (AX_T2, Cor_T1 etc.). I do see that in the `convert_DICOM_to_NIFTI ` [function](https://github.com/Svdvoort/DeepDicomSort/blob/master/Preprocessing/NIFTI_preparation_functions.py) the filename should take the subdirectories of the root, but not happening in this case unfortunately. Would be really good if you could point me out to what should be changed if you have a hunch. I just need to make sure I use the T2/T1s from the same session as you can guess,. 

Also, what is the 2nd 0 in the predictions ? ( I get 1 0 , 2 0). I am also getting an 8, which is not in the table I think.

**Comment by hajerkr** [comment]
> > 
> 
> Heya again, just wanted to circle back with regards to the final file naming used here. You mentioned that the final predictions will contain the full (original) path to the DICOM folder. But I'm getting the following:
> 
> `/home/hajerkr/NIFTI_SLICES/1053202153__20200129__MR__1.2.840.113654.2.70.1.313531726791507458836896066765452860929__1.2.840.113654.2.70.1.244649490914256453820682437713251151365_Scan_1_0.nii.gz`
> 
> In this case I am losing the SessionNum, under which all the DICOM folders are (AX_T2, Cor_T1 etc.). I do see that in the `convert_DICOM_to_NIFTI ` [function](https://github.com/Svdvoort/DeepDicomSort/blob/master/Preprocessing/NIFTI_preparation_functions.py) the filename should take the subdirectories of the root, but not happening in this case unfortunately. Would be really good if you could point me out to what should be changed if you have a hunch. I just need to make sure I use the T2/T1s from the same session as you can guess,.

I figured this part out, just extracted a few more things from the dicom header in the DPF script !

> Also, what is the 2nd 0 in the predictions ? ( I get 1 0 , 2 0). I am also getting an 8, which is not in the table I think.

**Comment by Svdvoort** [comment]
> Also, what is the 2nd 0 in the predictions ? ( I get 1 0 , 2 0). I am also getting an 8, which is not in the table I think.

The 2nd 0 is the 'ground truth' label. This is from the label file that is created which can normally be used for training. Since in this case there is no ground truth the 2nd column can simply be ignored. 

The 8 is actually correct, but there is a slight difference between the labels and the table. 
The CNN when applied predicts labels from 0 up to and including 7, but in the script I add +1 to each prediction to get labels ranging from 1 up to and including 8. I will add a new column to indicate this difference. (There should be no 0 in your prediction file). 
So 8 in this case is DSC.
