### ISSUE TITLE
Empty input file Scans_4D.Txt

### ISSUE THREAD

**Issue by rbareja25** [ErasmusMC-NeuroOnco/DeepDicomSort#27]
Hi,

I am working on running DeepDicomSort and have been able to set up the code.My run fails at Scans_4d.txt file.Could you please look into this?
I have provided all the permissions for the DATA folder.
I am attaching the screenshot for reference of my log from the run of `'python3 preprocessing_pipeline.py`'

<img width="1280" alt="Screen Shot 2023-05-23 at 1 14 10 PM" src="https://github.com/Svdvoort/DeepDicomSort/assets/128835038/55a56f34-ec8c-4dc4-9526-73f11460cf95">

Thanks,
Rohan

**Comment by Svdvoort** [comment]
Could you double check whether there are scans output in `brain_mri_bids/DATA`? 

From the earlier output it seems like scans are stored in `brain_mri_bids/TEMP`, and then it tries to read the `Scans_4D.txt` file from `brain_mri_bids/DATA` instead, whereas I would expect it to be also in `brain_mri_bids/TEMP`.

If there is data in the `brain_mri_bids/DATA` folder could you share your `config.yaml` file?

**Comment by rbareja25** [comment]
In the DATA folder, there is only labels.txt file which is not empty. The Scans_4D.txt file is empty.
<img width="917" alt="Screen Shot 2023-05-24 at 9 00 09 AM" src="https://github.com/Svdvoort/DeepDicomSort/assets/128835038/1e6f85aa-7dca-431c-9143-f53bf567f69e">

**Comment by Svdvoort** [comment]
Can you specify in which way exactly your run fails? 
The `Scans_4D.txt` can be an empty file - just means that there are no scans that are 4D. 
You indicate that your `labels.txt` is not empty. Then the last column there should just be all zeros.
Is this the case? Then the algorithm itself should just be able to run without problems. 
The pre-processing seems to have gone fine in this case, is there an error in actually running the algorithm? 
I need some more details about what exactly doesn't work as you expect to be able to actually resolve the issue.

It is giving a warning about an empty file in your first screenshot - but this is just a warning, it shouldn't have any effect on the rest of the processing and can be safely ignored.

**Comment by rbareja25** [comment]
Yes the labels.txt file has all zeros and the first column has the nifti file names.Ok so I will ignore the warning and continue with the rest of the steps. Thank you!
