### ISSUE TITLE
Unable to run inference using docker container

### ISSUE THREAD

**Issue by deepakri201** [ErasmusMC-NeuroOnco/DeepDicomSort#29]
Hi, 

I'm interested in using your scan classification method using Docker. I was able to pull the image, and created the appropriate input and output folders. However, I ran into the following errors: 

![image](https://github.com/Svdvoort/DeepDicomSort/assets/59979551/af40de96-195c-4f3a-a4e3-2e709f5565ef)

Thank you, 

Deepa

**Comment by Svdvoort** [comment]
Hi Deepa,

Are you sure that the path `/home/exouser/Documents/DeepDICOMSort/download/` contains DICOM/NIFTI images and is accessible by the docker (has the right permissions)? 
And whether the path `/home/exouser/Document/DeepDICOMSort/output` is a path that exists and is actually writeable?

Usually it is one of these problems, see also #22 

Sebastian

**Comment by deepakri201** [comment]
Hi Sebastian, 

Thank you for your quick response. You are right, I did not have my data organized the right way, and was not using the correct root folder in the docker run command. 

Thank you! 

Deepa

**Comment by Svdvoort** [comment]
Glad that it is working now, I'll close this issue then. Feel free to reopen it if problems will show up in the future again.
