### ISSUE TITLE
Orientation Names for Sort_Bids.py

### ISSUE THREAD

**Issue by ironb25** [ErasmusMC-NeuroOnco/DeepDicomSort#30]
Hello,

I wanted to check if it's possible to get orientations(Ax, Sag) for Nifti files once we get the predictions of predict_cnn.py.
Similar to what is happening in Rename_folders_from_predictions.py but for the Nifti files.

Thanks,
Rohan

**Comment by Svdvoort** [comment]
It is possible.
We get the orientation from the DICOM tags, you could update this to get the orientation from the NIFTI header, but that would require some additional work.
Another option would be to sort the DICOM files, and then match them back to the NIFTI files to get the orientation there. If you want to implement yourself I would suggest this second approach as it is a bit easier. 

However, both of these approaches are outside the scope of this repo. Would require quite some additional work and testing. Furthermore, the code is already quite old, and such implementation would be better suited in a new tool that would be built from the ground up.
