### ISSUE TITLE
Run ID's

### ISSUE THREAD

**Issue by ironb25** [ErasmusMC-NeuroOnco/DeepDicomSort#31]
Hello,

After running Sort_BIDS.py, I see that for e.g from a same patient with just 4 nifti's  created in the NIFTI folder, and also the dicom folder has onl6 6 scans for this case. but SORT_BIDS creates 12 BIDS annotated nifti's. Basically, each nifti has multiple run ID's, thereby generating 12 nifti annotated files.Are those duplicates? Any thoughts on this?

Thanks,
Rohan

**Comment by Svdvoort** [comment]
Did you perhaps run the `Sort_to_BIDS.py` script twice? If the files already exist then they just get assigned a new run id, there is no check whether they're the same file.

Could you perhaps delete all files from the BIDS folder and do a single run again just to check? If it once again produces 12 nifti's, is it possible to send the anonymized DICOMs so I could check them?

**Comment by ironb25** [comment]
Yes that was the issue, I might have run the script twice resulting in multiple runs.Thanks! Couple of issues more,First,  for some cases there are more dicom scans but nifti scans (NIFTI)folder results in lesser number of scans, scans get lost.Any reason you could think of? I can share the case if needed as its a public dataset. 

Secondly - in a dataset, I see the predict_cnn.py generated predictions for some cases, but running Sort_Bids.py does not generate BIDS folder for those cases. Those cases are present in all prior steps except the BIDS_SORTED.

**Comment by Svdvoort** [comment]
As for the less nifti scans then DICOM folders: often this is because the scans are for example localizers. These cannot be converted to NIFTI because of the weird structure they have. Often these scans only have 2-3 DICOM files, and are not usable for further processing so we don't take them into account. Could you check if this is the case, or if they are actually "real"/useful scans that you would like to have sorted? 

As for the BIDS missing data: what I can think of there is that there are predictions that are not included in the BIDS standard. For example the PWI DSC scans are not converted to BIDS, because (at least at the time this software was created) they did not have a corresponding element for these scans in BIDS. Thus, there is no way to provide the in BIDS format. Here I would advise you to check the predicted scan type and if it's either DERIVED or PWI_DSC, then it's simply because they don't have a corresponding item in the BIDS standard.

**Comment by ironb25** [comment]
Hi Sebastian - You are correct, there are very few dicoms for the ones that cant be converted to Nifti. so basically there is 1 scan per timepoint and 2 timepoints that seem to be usable., but I still end up with 2 nifti file predictions (T1 and T1GD) for both timepoints. I think either the scan will be one or the other since there is only 1 scan per timepoint.

And regarding the BIDS missing data, yes the case has predictions labeled "7" in the predictions file but there are also scans predicted to be T1Gd , and are labeled correctly by Rename_folder_predictions.py, basically the folder is created with T1Gd scan.Infact the DICOM_SORTED folder has all cases but BIDS missed 13 cases out of 49 cases.

**Comment by ironb25** [comment]
Regarding the first, I wanted to add more , I notice the scans labeled RTdose in raw dicom are maybe kind of being predicted as T1GD(post contrast).These scans also have 1-3 dicom files.SO maybe I should exclude them from the raw dicom itself?

**Comment by Svdvoort** [comment]
Yes excluding RTDose (and anything that is not MRI) is advisable before running the tool. These are not actually MRI scans, so the algorithm will never correctly predict them. 
Of course there are also valid MRI scans that DeepDicomSort is not able to predict, for example DCE perfusion. This is a shortcoming of the tool. 

For the BIDS data: if it is predicted as T1GD and there is a NIFTI file it is strange that it does not get converted to BIDS, this should not be a problem. Could you provide an example of that?

**Comment by ironb25** [comment]
I have excluded scans that are not MRI. e.g. scans with very few DICOM's. It seems the scans that are "DCE", "DSC" were converted to NIFTI, are being predicted as T1w.

I made changes in the code for Sort_BIDS.py. Basically if the case has anatomical scans and DCE scans etc, the case was 
completely skipped.Now, I am able to get the relevant scans converted to BIDS. I added if statements after line 117 for predictions 6 onwards.

Would you recommend filtering DCE,DSC scans prior to running Deep Dicom Sort?Any other types of scans that you would recommend from your experience to remove prior itself?

**Comment by Svdvoort** [comment]
DSC scans should be fine as they are part of the set of scans that DeepDicomSort can predict (of course it will not always be perfect though). DCE indeed is better to remove. Everything that is not part of the set that DeepDicomSort is trained on (see [the table here](https://github.com/ErasmusMC-NeuroOnco/DeepDicomSort?tab=readme-ov-file#running-deepdicomsort)) would be better to remove. 

However, if you already know these scan types of course there is less of a need to run DeepDicomSort. In practice usually I just run it on all scans, and then afterwards check the predictions as this in my experience is less time-consuming.

**Comment by ironb25** [comment]
Thank you, this was very helpful!
